let PRODUCTS=[],currentProduct=null,currentColorFolder="";const bagArea=document.querySelector("#bagArea"),readyArea=document.querySelector("#readyArea"),readyTitle=document.querySelector("#readyTitle"),tabs=document.querySelectorAll(".tabs button"),modal=document.querySelector("#modal"),loading=document.querySelector("#loading");
function parseCSV(t){const rows=[];let row=[],v="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c=='"'&&q&&n=='"'){v+='"';i++}else if(c=='"'){q=!q}else if(c==","&&!q){row.push(v);v=""}else if((c=="\n"||c=="\r")&&!q){if(v||row.length){row.push(v);rows.push(row);row=[];v=""}if(c=="\r"&&n=="\n")i++}else v+=c}if(v||row.length){row.push(v);rows.push(row)}const h=rows.shift().map(x=>x.trim().replace(/^\uFEFF/,""));return rows.map(r=>{const o={};h.forEach((k,i)=>o[k]=(r[i]||"").trim());return o})}
function parseColors(t){if(!t)return[];return t.split("|").map(x=>{const [label,folder]=x.split(":");return{label:(label||"").trim(),folder:(folder||"").trim()}}).filter(x=>x.label&&x.folder)}
function norm(r){return{id:r.id,category:r.category,categoryName:r.categoryName,name:r.name,price:r.price,shortDesc:r.shortDesc,desc:r.desc,folder:`assets/${r.folder}`,colors:parseColors(r.colors),options:r.options?r.options.split("|").map(v=>v.trim()):["상담 후 옵션 확인"],status:r.status||"show"}}
async function loadProducts(){try{const res=await fetch("products.csv?time="+Date.now());const txt=await res.text();PRODUCTS=parseCSV(txt).map(norm).filter(p=>p.status!="hide");loading.classList.add("hidden");renderBags()}catch(e){loading.textContent="products.csv를 불러오지 못했습니다. Live Server로 실행했는지 확인해주세요.";console.error(e)}}
function productImages(p,color=""){const base=color?`${p.folder}/${color}`:p.folder;const imgs=[`${base}/main.jpg`];for(let i=1;i<=9;i++)imgs.push(`${base}/detail${String(i).padStart(2,"0")}.jpg`);return imgs}
function renderBags(){const bags=PRODUCTS.filter(p=>p.category=="bag");if(!bags.length){bagArea.innerHTML=`<div class="ready"><h3>가방 상품 준비중</h3><p>products.csv에 상품을 추가해주세요.</p></div>`;return}bagArea.innerHTML=bags.map(p=>{const first=p.colors[0]?.folder||"";return`<article class="product-card" data-id="${p.id}"><div class="product-img"><img src="${productImages(p,first)[0]}" alt="${p.name}"></div><div class="product-info"><p class="gold">${p.categoryName}</p><h3>${p.name}</h3><div class="product-price">${p.price}</div><p>${p.shortDesc}</p><strong>상세 확인하기 ›</strong></div></article>`}).join("");document.querySelectorAll(".product-card").forEach(c=>c.onclick=()=>openDetail(c.dataset.id))}
function renderDetailImages(p,color=""){const imgs=productImages(p,color);document.querySelector("#bigImage").src=imgs[0];const list=document.querySelector("#thumbList");list.innerHTML=imgs.map((src,i)=>`<button class="thumb ${i==0?"active":""}" data-src="${src}"><img src="${src}" onerror="this.closest('button').remove()"></button>`).join("");list.querySelectorAll(".thumb").forEach(b=>b.onclick=()=>{list.querySelectorAll(".thumb").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelector("#bigImage").src=b.dataset.src})}
function openDetail(id){currentProduct=PRODUCTS.find(p=>p.id==id);if(!currentProduct)return;document.querySelector("#detailCategory").textContent=currentProduct.categoryName;document.querySelector("#detailName").textContent=currentProduct.name;document.querySelector("#detailPrice").textContent=currentProduct.price;document.querySelector("#detailDesc").textContent=currentProduct.desc;document.querySelector("#detailOption").innerHTML=currentProduct.options.map(o=>`<option>${o}</option>`).join("");const box=document.querySelector("#colorBox"),sel=document.querySelector("#detailColor");if(currentProduct.colors.length){box.classList.remove("hidden");sel.innerHTML=currentProduct.colors.map(c=>`<option value="${c.folder}">${c.label}</option>`).join("");currentColorFolder=currentProduct.colors[0].folder;sel.value=currentColorFolder;sel.onchange=()=>{currentColorFolder=sel.value;renderDetailImages(currentProduct,currentColorFolder)}}else{box.classList.add("hidden");sel.innerHTML="";currentColorFolder=""}renderDetailImages(currentProduct,currentColorFolder);modal.classList.add("show")}
tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.remove("active"));b.classList.add("active");if(b.dataset.cat=="bag"){bagArea.classList.remove("hidden");readyArea.classList.add("hidden")}else{bagArea.classList.add("hidden");readyArea.classList.remove("hidden");readyTitle.textContent=b.textContent+" 상품 준비중"}});
document.querySelector("#closeModal").onclick=()=>modal.classList.remove("show");document.querySelector("#modalBg").onclick=()=>modal.classList.remove("show");document.querySelector("#applyProduct").onclick=()=>{if(!currentProduct)return;const opt=document.querySelector("#detailOption").value;const color=currentProduct.colors.length?document.querySelector("#detailColor").selectedOptions[0].textContent:"기본";document.querySelector("#selectedProduct").value=`${currentProduct.name} / ${currentProduct.price} / 색상: ${color} / 옵션: ${opt}`;modal.classList.remove("show");location.hash="request"};loadProducts();